name: ai-week4-workshop
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - numpy<2
  - scikit-learn
  - pip
  - pip:
      - mediapipe==0.10.21
variables:
  PYTHONNOUSERSITE: "1"